name             'bsdcpio'
source_url       'https://github.com/sous-chefs/bsdcpio'
issues_url       'https://github.com/sous-chefs/bsdcpio/issues'
maintainer       'Sous Chefs'
maintainer_email 'help@sous-chefs.org'
chef_version     '>= 12.1'
license          'Apache-2.0'
description      'Installs bsdcpio'
version          '1.0.18'

supports 'ubuntu'
